services:
  caddy:
    build: .
    container_name: central_proxy
    restart: unless-stopped
    # Host mode allows Caddy to see 'localhost' ports opened by other stacks
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ACME_AGREE=true
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}

volumes:
  caddy_data:
  caddy_config: