{
 "title": "Finanzen",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "Jahr",
    "query": "SELECT\n    substr(date, 1, 4) as Datum\nFROM v_transactions\nGROUP BY Datum;"
   }
  ]
 },
 "panels": [
  {
   "title": "Net worth $year",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT SUM(amount/100.0) from v_transactions where substr(date, 1, 4)<=\"$year\";",
     "rawQueryText": "SELECT SUM(amount/100.0) from v_transactions where substr(date, 1, 4)<=\"$year\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Scorecard Net Worth $year",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MIN(SUM(amount/100.0)/50000*100,100) as \"€50k\", MIN(SUM(amount/100.0)/100000*100,100) as \"€100k\", MIN(SUM(amount/100.0)/250000*100,100) as \"€250k\", MIN(SUM(amount/100.0)/500000*100,100) as \"€500k\" from v_transactions where substr(date, 1, 4)<=\"$year\";",
     "rawQueryText": "select MIN(SUM(amount/100.0)/50000*100,100) as \"€50k\", MIN(SUM(amount/100.0)/100000*100,100) as \"€100k\", MIN(SUM(amount/100.0)/250000*100,100) as \"€250k\", MIN(SUM(amount/100.0)/500000*100,100) as \"€500k\" from v_transactions where substr(date, 1, 4)<=\"$year\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Essenskosten $year",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "queryText": "SELECT \n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    (SELECT -SUM(amount/100.0) from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='5314f2dc-6129-4d47-a973-244a178fcffd') as Lebensmittelkauf,\n    (SELECT -SUM(amount/100.0) from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='c8114bc7-9944-4b96-838d-d9e46796e7c0') as Bestellen\nFROM v_transactions t1\nWHERE substr(date, 1, 4)=\"$year\"\nGROUP BY Datum\nORDER BY date;",
     "rawQueryText": "SELECT \n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    (SELECT -SUM(amount/100.0) from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='5314f2dc-6129-4d47-a973-244a178fcffd') as Lebensmittelkauf,\n    (SELECT -SUM(amount/100.0) from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='c8114bc7-9944-4b96-838d-d9e46796e7c0') as Bestellen\nFROM v_transactions t1\nWHERE substr(date, 1, 4)=\"$year\"\nGROUP BY Datum\nORDER BY date;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Sondertilgung Ausreizung $year",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select 10500-SUM(amount/100.0) as Offen,SUM(amount/100.0) as Getilgt from v_transactions where account='8ce34628-6c31-4315-80bd-3fe4eef050d7' and category='f89fe60f-c0da-4015-b031-ccfd76255ccd' and substr(date, 1, 4)=\"$year\";",
     "rawQueryText": "select 10500-SUM(amount/100.0) as Offen,SUM(amount/100.0) as Getilgt from v_transactions where account='8ce34628-6c31-4315-80bd-3fe4eef050d7' and category='f89fe60f-c0da-4015-b031-ccfd76255ccd' and substr(date, 1, 4)=\"$year\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Kosten nach Kategorie Girokonto $year",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "queryText": "SELECT\n    v_categories.name as category,\n    -sum(v_transactions.amount/100.0)  as amount\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nWHERE account='485a9e8d-1476-4d31-b9c0-193443dc9978' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != '5d31f7ee-0b38-47f5-bbe0-416d8d468a60' AND substr(date, 1, 4)=\"$year\"\ngroup by category\nORDER BY amount desc;",
     "rawQueryText": "SELECT\n    v_categories.name as category,\n    -sum(v_transactions.amount/100.0)  as amount\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nWHERE account='485a9e8d-1476-4d31-b9c0-193443dc9978' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != '5d31f7ee-0b38-47f5-bbe0-416d8d468a60' AND substr(date, 1, 4)=\"$year\"\ngroup by category\nORDER BY amount desc;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Kosten nach Kategorie Gemeinschaftskonto $year",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "queryText": "SELECT\n    v_categories.name as category,\n    -sum(v_transactions.amount/100.0)  as amount\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nWHERE account='46746a7c-0eff-4702-a081-5cef893afce9' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != 'cf607948-1034-412a-8a21-72a9dc761c5f' AND amount < 0 AND substr(date, 1, 4)=\"$year\"\ngroup by category\nORDER BY amount desc;",
     "rawQueryText": "SELECT\n    v_categories.name as category,\n    -sum(v_transactions.amount/100.0)  as amount\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nWHERE account='46746a7c-0eff-4702-a081-5cef893afce9' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != 'cf607948-1034-412a-8a21-72a9dc761c5f' AND amount < 0 AND substr(date, 1, 4)=\"$year\"\ngroup by category\nORDER BY amount desc;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Sparquote aktueller Monat",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Euro (€)" } },
   "targets": [
    {
     "queryText": "select amount/100.0 as Sparen from v_transactions where category='182c3391-7cb6-46a6-b382-0c58952bd354' ORDER BY date DESC LIMIT 1;",
     "rawQueryText": "select amount/100.0 as Sparen from v_transactions where category='182c3391-7cb6-46a6-b382-0c58952bd354' ORDER BY date DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Kosten nach Monat $year",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "queryText": "SELECT\n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    -sum(v_transactions.amount/100.0)  as amount,\n    accounts.name account, \n    v_categories.name as category,\n    v_categories.is_income,\n    v_transactions.notes,\n    v_transactions.date\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nJOIN \n    accounts\nON \n    v_transactions.account = accounts.id\nWHERE account='485a9e8d-1476-4d31-b9c0-193443dc9978' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != '5d31f7ee-0b38-47f5-bbe0-416d8d468a60' AND substr(date, 1, 4)=\"$year\"\ngroup by category, Datum\nORDER BY date;",
     "rawQueryText": "SELECT\n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    -sum(v_transactions.amount/100.0)  as amount,\n    accounts.name account, \n    v_categories.name as category,\n    v_categories.is_income,\n    v_transactions.notes,\n    v_transactions.date\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nJOIN \n    accounts\nON \n    v_transactions.account = accounts.id\nWHERE account='485a9e8d-1476-4d31-b9c0-193443dc9978' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != '5d31f7ee-0b38-47f5-bbe0-416d8d468a60' AND substr(date, 1, 4)=\"$year\"\ngroup by category, Datum\nORDER BY date;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Durchschnittliche Quote Sparen/Gehalt Trend 6 Monate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "SELECT\n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    CASE \n        WHEN (SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='182c3391-7cb6-46a6-b382-0c58952bd354') IS NULL OR (SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='3c1699a5-522a-435e-86dc-93d900a14f0e') IS NULL THEN 0\n        ELSE ROUND(((SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='182c3391-7cb6-46a6-b382-0c58952bd354') * 1.0) / (SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='3c1699a5-522a-435e-86dc-93d900a14f0e') * 100, 2)\n    END as percentage\nFROM v_transactions t1\nWHERE substr(date, 1, 4) || substr(date, 5, 2) || substr(date, 7, 2) > substr(date('now','-6 months'), 1, 4) || substr(date('now','-6 months'), 6, 2) || substr(date('now','-6 months'), 9, 2) AND substr(date, 5, 2) != substr(date(), 6, 2)\nGROUP BY Datum\nORDER BY date;",
     "rawQueryText": "SELECT\n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    CASE \n        WHEN (SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='182c3391-7cb6-46a6-b382-0c58952bd354') IS NULL OR (SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='3c1699a5-522a-435e-86dc-93d900a14f0e') IS NULL THEN 0\n        ELSE ROUND(((SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='182c3391-7cb6-46a6-b382-0c58952bd354') * 1.0) / (SELECT amount/100.0 from v_transactions t2 where substr(t2.date, 1, 6)=substr(t1.date, 1, 6) and category='3c1699a5-522a-435e-86dc-93d900a14f0e') * 100, 2)\n    END as percentage\nFROM v_transactions t1\nWHERE substr(date, 1, 4) || substr(date, 5, 2) || substr(date, 7, 2) > substr(date('now','-6 months'), 1, 4) || substr(date('now','-6 months'), 6, 2) || substr(date('now','-6 months'), 9, 2) AND substr(date, 5, 2) != substr(date(), 6, 2)\nGROUP BY Datum\nORDER BY date;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Durchschnittliche Kosten 12 Monate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "SELECT\n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    -sum(amount/100.0) as amount\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nWHERE account='485a9e8d-1476-4d31-b9c0-193443dc9978' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != '5d31f7ee-0b38-47f5-bbe0-416d8d468a60' AND substr(date, 1, 4) || substr(date, 5, 2) || substr(date, 7, 2) > substr(date('now','-12 months'), 1, 4) || substr(date('now','-12 months'), 6, 2) || substr(date('now','-12 months'), 9, 2) AND substr(date, 5, 2) != substr(date(), 6, 2)\ngroup by Datum\nORDER BY date;",
     "rawQueryText": "SELECT\n    substr('JanFebMarAprMayJunJulAugSepOctNovDec', 1 + 3*substr(date, 5, 2), -3) || ' ' || substr(date, 3, 2) as Datum,\n    -sum(amount/100.0) as amount\nFROM \n    v_transactions\nJOIN \n    v_categories \nON \n    v_transactions.category = v_categories.id\nWHERE account='485a9e8d-1476-4d31-b9c0-193443dc9978' AND is_income=0 AND category != '182c3391-7cb6-46a6-b382-0c58952bd354' AND category != '5d31f7ee-0b38-47f5-bbe0-416d8d468a60' AND substr(date, 1, 4) || substr(date, 5, 2) || substr(date, 7, 2) > substr(date('now','-12 months'), 1, 4) || substr(date('now','-12 months'), 6, 2) || substr(date('now','-12 months'), 9, 2) AND substr(date, 5, 2) != substr(date(), 6, 2)\ngroup by Datum\nORDER BY date;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Asset Allocation $year",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  (SELECT SUM(amount/100.0) from v_transactions where account='33fba22d-2bca-4e2c-aacc-f11818b9fb8c' and substr(date, 1, 4)<=\"$year\") as ETFs,\n  (SELECT SUM(amount/100.0) from v_transactions where account='2b078462-c6fe-4fa3-9608-263f6bff40c2' and substr(date, 1, 4)<=\"$year\") as bAV,\n  (SELECT SUM(amount/100.0) from v_transactions where account in ('485a9e8d-1476-4d31-b9c0-193443dc9978','2fbd0039-a275-4836-85c3-583c41ec5b1b', 'd05e55b2-d75d-459a-b85f-a262e5d79a54', '6d86b807-ab3a-43d9-aeb6-82b34da41aeb', '52473ef9-5805-442a-9f71-0f676bcb5fd6') and substr(date, 1, 4)<=\"$year\") as 'Tagesgeld/Festgeld/Cash'    \nLIMIT 1;",
     "rawQueryText": "SELECT \n  (SELECT SUM(amount/100.0) from v_transactions where account='33fba22d-2bca-4e2c-aacc-f11818b9fb8c' and substr(date, 1, 4)<=\"$year\") as ETFs,\n  (SELECT SUM(amount/100.0) from v_transactions where account='2b078462-c6fe-4fa3-9608-263f6bff40c2' and substr(date, 1, 4)<=\"$year\") as bAV,\n  (SELECT SUM(amount/100.0) from v_transactions where account in ('485a9e8d-1476-4d31-b9c0-193443dc9978','2fbd0039-a275-4836-85c3-583c41ec5b1b', 'd05e55b2-d75d-459a-b85f-a262e5d79a54', '6d86b807-ab3a-43d9-aeb6-82b34da41aeb', '52473ef9-5805-442a-9f71-0f676bcb5fd6') and substr(date, 1, 4)<=\"$year\") as 'Tagesgeld/Festgeld/Cash'    \nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}