---
- name: Configure Proxmox Host
  hosts: all
  become: true
  gather_facts: yes
  vars:
    # These will be injected by the deploy script
    tf_user: "{{ terraform_user }}"
    tf_password: "{{ terraform_password }}"
  
  tasks:
    - name: Configure Permanent Wake-on-LAN (Link File)
      copy:
        dest: /etc/systemd/network/50-wired.link
        owner: root
        group: root
        mode: '0644'
        content: |
          [Match]
          MACAddress={{ host_mac }}

          [Link]
          NamePolicy=kernel database onboard slot path
          MACAddressPolicy=persistent
          WakeOnLan=magic
      register: wol_config

    - name: Restart systemd-networkd to apply WOL settings
      systemd:
        name: systemd-networkd
        state: restarted
      when: wol_config.changed

    - name: Ensure enterprise repo file is not present
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.sources
        state: absent

    - name: Ensure enterprise ceph repo file is not present
      file:
        path: /etc/apt/sources.list.d/ceph.sources
        state: absent

    - name: Add No-Subscription Repo
      apt_repository:
        repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
        state: present

    - name: Update System
      apt:
        update_cache: yes
        upgrade: dist
    
    - name: Install Python Utils
      apt:
        pkg: [python3-proxmoxer, libguestfs-tools]

    - name: Disable 'No Valid Subscription' Popup
      replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: "res\\.data\\.status\\.toLowerCase\\(\\) !== 'active'"
        replace: "false"
        backup: yes
      register: pve_popup_patch

    - name: Restart PVE Proxy (Apply UI Changes)
      service:
        name: pveproxy
        state: restarted
      when: pve_popup_patch.changed

    - name: Ensure Terraform Role Exists
      command: pveum role add TerraformProv
      register: role_add
      # Fail only if error is NOT "already exists"
      failed_when: role_add.rc != 0 and "already exists" not in role_add.stderr
      changed_when: role_add.rc == 0

    - name: Enforce Terraform Role Permissions
      command: 
        argv:
          - pveum
          - role
          - modify
          - TerraformProv
          - -privs
          - "VM.Allocate VM.Config.CPU VM.Config.Disk VM.Config.Memory VM.Config.Network VM.Config.Options VM.Audit Datastore.AllocateSpace Datastore.Audit User.Modify Pool.Allocate Pool.Audit Sys.Audit Sys.Console Sys.Modify VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.HWType VM.Migrate VM.PowerMgmt SDN.Use VM.GuestAgent.Audit VM.Console"
      register: role_mod
      changed_when: role_mod.rc == 0

    - name: Create Terraform User
      command: pveum user add "{{ tf_user }}@pve" -password "{{ tf_password }}"
      register: user_cmd
      failed_when: user_cmd.rc != 0 and "already exists" not in user_cmd.stderr

    - name: Assign Terraform user to role
      command: pveum acl modify / -user "{{ tf_user }}@pve" -role TerraformProv
      register: usermod_cmd
      failed_when: usermod_cmd.rc != 0 and "already exists" not in usermod_cmd.stderr

    - name: Download Debian Image
      get_url:
        url: https://cloud.debian.org/images/cloud/{{ ansible_distribution_release }}/latest/debian-13-genericcloud-amd64.qcow2
        dest: /var/lib/vz/template/iso/debian-13-genericcloud-amd64.qcow2

    - name: Install QEMU Guest Agent In Image
      command: 
        argv:
          - virt-customize
          - -a
          - /var/lib/vz/template/iso/debian-13-genericcloud-amd64.qcow2
          - --update
          - --install
          - qemu-guest-agent
          - --run-command
          - systemctl enable qemu-guest-agent
          - --run-command
          - systemctl start qemu-guest-agent
      register: virt_cust
      changed_when: "'Installing: qemu-guest-agent' in virt_cust.stdout"

    - name: Verify qemu-guest-agent is installed in image
      command: >
        virt-ls -a /var/lib/vz/template/iso/debian-13-genericcloud-amd64.qcow2 /usr/sbin/
      register: image_files

    - name: Check if qemu-ga is present
      debug:
        msg: "qemu-guest-agent appears to be installed"
      when: "'qemu-ga' in image_files.stdout"

    - name: Warning if qemu-ga not found
      debug:
        msg: "WARNING: qemu-ga binary not found in image!"
      when: "'qemu-ga' not in image_files.stdout"

    - name: Destroy existing Template debian-cloud-template 9000
      command: qm destroy 9000 --purge true
      ignore_errors: yes

    - name: Create VM Template from Cloud Image
      shell: |
        qm create 9000 --memory 2048 --core 2 --name debian-cloud-template --net0 virtio,bridge=vmbr0
        # Import the patched disk into local-lvm
        qm importdisk 9000 /var/lib/vz/template/iso/debian-13-genericcloud-amd64.qcow2 local-lvm
        qm set 9000 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9000-disk-0
        qm set 9000 --boot order=scsi0
        qm set 9000 --ide2 local-lvm:cloudinit        
        qm set 9000 --serial0 socket --vga serial0
        qm set 9000 --agent enabled=1
        qm resize 9000 scsi0 +4G
        qm set 9000 --ipconfig0 ip=dhcp
        qm template 9000